### ISSUE TITLE
Issues to be solve 14/05/2015

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#1]
- [x] The block for Tweets and News needs to be merged.
- [x] The block FAQ should be Rename as About
- [x] The block News should be renamed to Related Tools, we will talk there about the Web services and the API.
- [x] Remove from the Bar options the "About the DDI"
- [x] We need to look for an Icon for the project.
- [x] We need to add a Help page or pages.
- [x] We need to add a Page for API with some text and examples of the API.
- [x] Create Twitter Account to link the DDI Project.
- [x] Add an option in the option bar about the databases like RNACentral is doing. 
- [x] Recall from Repo to Databases.

**Comment by ypriverol** [comment]
The DDIndex account was created https://twitter.com/DDIndex.

**Comment by baimingze** [comment]
that is great! Now there is one thing we need for the tweets is an id.
After we click here [https://twitter.com/settings/widgets] and create a
timeline, then we can get the id.

mingze


Yasset Perez-Riverol <notifications@github.com>于2015年5月14日周四 下午11:20写道：
