### ISSUE TITLE
The relevance sorting does not work

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#10]
@baimingze The relevance sorting does not work

**Comment by baimingze** [comment]
"{"diagnostics":{"message":"The sort field id 'relevance' does not exist."}}"

Ebeye search comes for the field named "relevance", it is not same as we thought before.

**Comment by baimingze** [comment]
I 'd removed the "relevance" sorting option from browse page. After we get this through from EBeye search, I think we can add it back.
