### ISSUE TITLE
metadata link in datasest

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#101]
@baimingze I noticed that the canonical link meta tag might not be populating correctly, atm it looks like:

<link rel="canonical" href={{meta_originalURL}}>
(this is from the source of page http://www.omicsdi.org/#/dataset/PRIDE/PXD001483 )

**Comment by baimingze** [comment]
I have found a possible solution for this issue, but I can't test it in local machine.
http://stackoverflow.com/questions/34629273/output-json-ld-with-anugularjs-for-structured-data-markup

**Comment by ypriverol** [comment]
@baimingze we can leave this issue for the end.

**Comment by ypriverol** [comment]
@baimingze try to include this into the code and we will see what happen when we put that into the web.

**Comment by ypriverol** [comment]
With the implementation of JMC this issue is solve.
