### ISSUE TITLE
Mozilla Firefox issue with web 

### ISSUE THREAD

**Issue by abb44** [BD2K-DDI/ddi-web-app#102]
![screenshot from 2016-08-03 11-15-50](https://cloud.githubusercontent.com/assets/20402784/17362149/aba4ee0a-596b-11e6-8ad7-902c328945aa.png)

**Comment by baimingze** [comment]
Dear abb44, could you please check it again?  One of the reasons is the firefox is still waiting for the data form web server. By the way, it works fine on my firefox. 

![omicsdi org on firefox](https://cloud.githubusercontent.com/assets/3970400/17388854/7b4ebe72-5a31-11e6-8ac8-4c383f4fb96e.png)

**Comment by abb44** [comment]
I'm using the version Firefox 44 and after 30 minutes the problem still remain.

**Comment by abb44** [comment]
We try 47 and it is working. Probably is the version of Firefox. Would be good to create a page with known issues.

**Comment by baimingze** [comment]
It's because of the order of the function definition and invoking. I have changed the order.
