### ISSUE TITLE
http://localhost:8080/dataset/pride/PXD000561

### ISSUE THREAD

**Issue by mindcrusher11** [BD2K-DDI/ddi-web-app#105]
I am getting errors frequently while accessing dataset 

org.springframework.web.util.NestedServletException: Request processing failed; nested exception is org.json.JSONException: Expected a ',' or ']' at 62 [character 63 line 1]
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:982)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.omicsdi.springmvc.configuration.CORSFilter.doFilter(CORSFilter.java:22)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
root cause

org.json.JSONException: Expected a ',' or ']' at 62 [character 63 line 1]
	org.json.JSONTokener.syntaxError(JSONTokener.java:451)
	org.json.JSONArray.<init>(JSONArray.java:130)
	org.json.JSONTokener.nextValue(JSONTokener.java:383)
	org.json.JSONObject.<init>(JSONObject.java:215)
	org.json.JSONObject.<init>(JSONObject.java:319)
	org.omicsdi.springmvc.http.DataProcess.get_section(DataProcess.java:130)
	org.omicsdi.springmvc.http.DataProcess.splitByEnrichmentInfo(DataProcess.java:61)
	org.omicsdi.springmvc.controller.DatasetGetContextController.getContext(DatasetGetContextController.java:40)
	sun.reflect.GeneratedMethodAccessor56.invoke(Unknown Source)
	sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke(Method.java:498)
	org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:221)
	org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
	org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:114)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	org.omicsdi.springmvc.configuration.CORSFilter.doFilter(CORSFilter.java:22)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by ypriverol** [comment]
@mindcrusher11 can you let @Ricardo-Ke know which dataset?

**Comment by mindcrusher11** [comment]
I am getting in multiple datasets sometimes , above link in Title is also one of dataset

**Comment by Ricardo-Ke** [comment]
@mindcrusher11 @ypriverol thanks,that's what we also face, something is wrong with logic getting meta_title or meta_abstract rewrited by java, we're resolving

**Comment by Ricardo-Ke** [comment]
has resolved, please pull and test
