### ISSUE TITLE
can not access "/dataset/gpmdb/GPM11210002594"

### ISSUE THREAD

**Issue by baimingze** [BD2K-DDI/ddi-web-app#106]
@Ricardo-Ke  The reason of this issue is the "diversity" of the domain's name. I have using a mapping to deal this issue in JS codes:

https://github.com/BD2K-DDI/ddi-web-app/blob/master/src/main/webapp/js/DDIDatasetCtl.js#L49

    $scope.domain_enrichedDatabase_map = {
        'metabolomics_workbench': 'MetabolomicsWorkbench',
        'gpmdb': 'GPMDB',
        'ega': 'EGA',
    };

https://github

.com/BD2K-DDI/ddi-web-app/blob/master/src/main/webapp/js/DDIDatasetCtl.js#L67

    //change the domain name to the real name in enrichment data in MongoDB
    var tempDomainName = $scope.domain;
    if ($scope.domain_enrichedDatabase_map[$scope.domain] == null) {
        tempDomainName = $scope.domain;
    }
    else {
        tempDomainName = $scope.domain_enrichedDatabase_map[$scope.domain];
    }

**Comment by Ricardo-Ke** [comment]
We've got the reason, another issue will be open for this **bug**
