### ISSUE TITLE
The database links

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#11]
@baimingze All the databases should link to the original resource using the Original url of the resource for example:

 PRIDE - http://www.ebi.ac.uk/pride/archive/
 PeptideAtlas - http://www.peptideatlas.org/
 MetaboLights - http://www.ebi.ac.uk/metabolights/
 MassiVE - https://massive.ucsd.edu/ProteoSAFe/datasets.jsp
 Metabolome Workbench - http://www.metabolomicsworkbench.org/

**Comment by baimingze** [comment]
done
