### ISSUE TITLE
When a Tag is clicked the search should be done again the tagging

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#112]
Hi all:
 When a Tag is clicked the search can't be done against all the data like http://www.omicsdi.org/#/search?q=%22%20phosphorylation%22 . If a tag is clicked the search should be done against the tags.

**Comment by Ricardo-Ke** [comment]
check the latest version,i'm ok locally

**Comment by ypriverol** [comment]
What mean I'm locally? The latest version is the JMV branch?

**Comment by baimingze** [comment]
I guess he wanted to say : The test on his local computer is all passed :).

**Comment by ypriverol** [comment]
Ok the code is commited?

**Comment by baimingze** [comment]
yes!
