### ISSUE TITLE
Most accessed datasets showing the repository

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#115]
For some reason the most accessed datasets box is showing the provider database. 
<img width="337" alt="screen shot 2016-10-24 at 10 11 19" src="https://cloud.githubusercontent.com/assets/52113/19639929/68f407e2-99d2-11e6-8b76-3d1ab332e308.png">

See for the first one the pride at the end.

**Comment by baimingze** [comment]
fixed
