### ISSUE TITLE
Datasets on Databases pages not working

### ISSUE THREAD

**Issue by mindcrusher11** [BD2K-DDI/ddi-web-app#118]
![image](https://cloud.githubusercontent.com/assets/2452982/19641845/6bcd4dcc-99da-11e6-836d-7f82af7abcec.png)

**Comment by Ricardo-Ke** [comment]
Hi @mindcrusher11 , please describe your issue about database pages precisely.
it won't open or any other errors?

**Comment by mindcrusher11** [comment]
sorry i think I pasted wrong pic 

![image](https://cloud.githubusercontent.com/assets/2452982/19647239/15007ef4-99f5-11e6-868c-829f42bbef73.png)

if you click on datasets in above pic it is not working as it is pointing to wrong url anyways I have fixed it now .
