### ISSUE TITLE
Change in the dataset web page

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#122]
Henning suggestion and I vote +1 that we should make more clear the link to the original PROVIDER . 

<img width="763" alt="screen shot 2016-10-24 at 14 19 22" src="https://cloud.githubusercontent.com/assets/52113/19647352/955eb390-99f5-11e6-8aa5-23eae0c0eec3.png">

The I suggest the following changes: 

Add a something like: 

**Provider**: ExpressionAtlas | E-GEOD-30999 | 2015-07-28

Behind that I would like to have a button like this with different colour. 

<img width="194" alt="screen shot 2016-10-24 at 14 14 56" src="https://cloud.githubusercontent.com/assets/52113/19647727/5be3af1a-99f7-11e6-8b69-6cd700320ffa.png">

where we can forward the user to the original dataset.

**Comment by Ricardo-Ke** [comment]
should i give the same style to date(2015-07-28)?

**Comment by ypriverol** [comment]
the provider should be like: 

**Provider**: ExpressionAtlas | E-GEOD-30999 | 2015-07-28 

But if you like you want to change the date like 28-07-2015 because it nicer to read.

**Comment by Ricardo-Ke** [comment]
already pushed, please check and close this issue

**Comment by ypriverol** [comment]
Well done
