### ISSUE TITLE
JSON-LD Tags missing. 

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#129]
Hi all, @mindcrusher11 and myself did a first test in production of the new web. Excellent work of @Ricardo-Ke BTW. Here some issues that needs to be fixed. Some minor comments: 
- [ ] JSON-LD for datatasets should contain the [following properties](https://developers.google.com/search/docs/data-types/datasets): This are still missing: **description** (description of the dataset), **url** (the omicsdi url), **sameAs** (this filed should contain other urls), for example the original dataset url, **keywords**(dataset keywords, we have this information, see the browse page), **variableMeasured**(here we will put for now the omicsType), **creator.name**(we can add here the submitter information, also we can add all the publication authors), **citation**(if the publication is provided please add this field).

**Comment by ggcong** [comment]
I am not very clearly about the property " sameAs",may i get an example?

**Comment by ggcong** [comment]
"sameAs" shoule like this one "https://www.ebi.ac.uk/arrayexpress/experiments/E-MTAB-4561"?

**Comment by ypriverol** [comment]
sameAs is the url from the original provider for example for dataset: 
 
http://www.omicsdi.org/dataset/pride/PXD001020

would be http://www.ebi.ac.uk/pride/archive/projects/PXD001020

**Comment by ggcong** [comment]
I have filled json-ld ,and it has passed the google structure tool 's test ,and i delete all "#" in all urls which contains  "www.omicsdi.org",it works  well same

**Comment by ggcong** [comment]
I  hava a view that how about we add a default keyword "dataset"  if that dataset has no kewords or it shows like "not avaliable"  in  http://www.omicsdi.org/ws/dataset/get?acc=PRD000269&database=pride

**Comment by ypriverol** [comment]
if the dataset do not have keywords. do not add the field.

**Comment by ypriverol** [comment]
For the citation @mindcrusher11 we should add this schema for now:

<img width="660" alt="screen shot 2016-10-26 at 10 47 30" src="https://cloud.githubusercontent.com/assets/52113/19721314/a686ca0c-9b69-11e6-9e49-90cbd44046b6.png">

This is: Authors, Year of the publication, Title of the dataset, Database, version (for all of our datasets) will be V1, original url to the provider.

**Comment by baimingze** [comment]
@data{  ST000106,
authors = {a1, a2},
PublicationData = {2012.08},
TitleOfTheDataset = {IWMS Study 1 Weight comparison of obese and lean patients},
Database = {MetabolomicsWorkbench},
version = {V1},
originalUrl = {http://www.metabolomicsworkbench.org/data/DRCCMetadata.php?Mode=Study&StudyID=ST000106}
      
}
