### ISSUE TITLE
Errors in the metadata tags

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#130]
After the first iteration we found a couple of errors in the metadata tags: 

- [ ]  The url of the dataset is encoded with # (see example: href="http://www.omicsdi.org/#/dataset/ArrayExpress/E-GEOD-46604"). 

- [ ] for the metadata tags we should called like 
               dataset_title -> title 
               dataset_abstract -> description
               dataset_identifier -> identifier
- [ ] It would be nice to remove the general description from the datatset pages <meta content="OmicsDI is a integrate resource to multiple omics repositories, including Proteomics, Metabolomics and Genomics" name="description">

**Comment by mindcrusher11** [comment]
fixed url ,removed description and metadata tags
