### ISSUE TITLE
Error in margin

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#131]
We have a new bug in the margin, see the example. This new error was introduced recently

<img width="739" alt="screen shot 2016-10-25 at 16 15 12" src="https://cloud.githubusercontent.com/assets/52113/19692060/66d165c0-9ace-11e6-9e6c-b773f403bc72.png">

Also, I found interesting that the following dataset do not have provider database or date. 

http://www.omicsdi.org/dataset/metabolomics_workbench/ST000122

**Comment by Ricardo-Ke** [comment]
already resolved, please check and close this issue:)

**Comment by mindcrusher11** [comment]
@Ricardo-Ke  I have few suggestions can you align 

INSTRUMENT(S): 
ORGANISM(S): 
TISSUE(S): 
Provider: PXD001020 | PRIDE | 01-07-2014

with 

ABSTRACT ,SAMPLE PROTOCOL and DATA PROTOCOL.

also align ACCESS_BUTTON with JSON and XML but position should be on left and color should be same of title bar of Home page.

**Comment by Ricardo-Ke** [comment]
the ACCESS BUTTON with  JSON and XML are In a horizontal line？

**Comment by mindcrusher11** [comment]
yes

**Comment by Ricardo-Ke** [comment]
check modified styles

**Comment by mindcrusher11** [comment]
yes it is better
