### ISSUE TITLE
Error in Dataset

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#133]
http://www.omicsdi.org/dataset/ega/EGAO00000000061

**Comment by ggcong** [comment]
it had been fixed

**Comment by ypriverol** [comment]
http://www.omicsdi.org/dataset/arrayexpress-repository/E-GEOD-28135 Another here @ggcong

**Comment by ypriverol** [comment]
Another broken http://www.omicsdi.org/dataset/metabolights_dataset/MTBLS11 @ggcong

**Comment by ypriverol** [comment]
Another broken http://www.omicsdi.org/dataset/pride/PXD004280

**Comment by ggcong** [comment]
sorry for this ,actually i did it days ago ,but forget  push ,all them  are caused by json format, so i add catch jsonException , now it has been fixed
