### ISSUE TITLE
Missing text on Firefox/49.0

### ISSUE THREAD

**Issue by sneumann** [BD2K-DDI/ddi-web-app#136]
Screenshot from:
Build identifier: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:49.0) Gecko/20100101 Firefox/49.0

![screenshot from 2016-11-15 16-58-28](https://cloud.githubusercontent.com/assets/195385/20312757/f459bdd4-ab54-11e6-9c21-e16cbb89d807.png)

Yours, Steffen

**Comment by ypriverol** [comment]
@sneumann thanks for reporting this issue. We already fixed it, please feel free to participate and suggest use cases in omicsdi

**Comment by sneumann** [comment]
Hi, unfortunately it still has no visible text. I can cut&paste 
from where text should be, and I get the stuff below. 
I also hit ctrl-reload, and even restarted firefox. 
Yours, Steffen
```
[Transcriptomics] Sep 25 Transcription profiling of Set2 deletion in yeast to investigate how H3K36 methylation affects mRNA transcription during carbon source shifts
[Transcriptomics] Sep 25 Genome-wide identification of bZIP29 & bZIP69 target genes in Arabidopsis cell cultures
[Transcriptomics] Sep 25 Genome-wide transcriptome analysis bZIP29 dominant negative repressor line in root tips of Arabidopsis
[Transcriptomics] Sep 25 Identification of proteins interacting with lncRNA Braveheart in mouse using protein microarray
[Transcriptomics] Sep 24 Transcription profiling by array of FOXP3 overexpression in resting and activated mouse CD4+ T cells
```

**Comment by ypriverol** [comment]
Sorry. We need to wait to the next release ;)
