### ISSUE TITLE
facet should be hiden if not information is provided

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#137]
@baimingze @Ricardo-Ke 

I have been looking other services an when not facet value is provided, we should hide the corresponding block. This will enable in the future to grow the number of facet boxes and make easier the search. Also in the future some omics and provider will have facets that others do not have making strong and consistent the layout. For example if I search in the future for http://www.omicsdi.org/search?q=%22loco%20como%20loco%22 I should expect no boxes because no data is available. What do you think?

**Comment by baimingze** [comment]
done
