### ISSUE TITLE
Problem with abstract description

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#140]
Abstract is repeated. Please fix as soon as possible. 

<img width="808" alt="screen shot 2016-12-05 at 07 17 09" src="https://cloud.githubusercontent.com/assets/52113/20876571/07a04aa0-babb-11e6-8bc3-042b347d86f4.png">

**Comment by baimingze** [comment]
I will check on it

**Comment by Ricardo-Ke** [comment]
done.
The repeated section was rendered by server and tested whether crawler consider it as empty pages

**Comment by baimingze** [comment]
Great, thanks Ricardo.
