### ISSUE TITLE
Long search do not work

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#141]
If a search for: 

http://www.omicsdi.org/search?q=TAXONOMY:%225833%22%20OR%20TAXONOMY:%2236329%22%20OR%20TAXONOMY:%225821%22%20OR%20TAXONOMY:%225823%22

and then I click proteomics that contains 9 results. It will go to an empty page. 

Regards 
Yasset

**Comment by ypriverol** [comment]
Is this fix included in the advance search query builder?

**Comment by baimingze** [comment]
If we pull this JMC code to the JMC-adv-search branch, and do a little
change, then the advance search query builder will be ready.

Will do it hours later.
