### ISSUE TITLE
Icon for the project 

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#15]
The current Icon is really bad.

**Comment by ypriverol** [comment]
@baimingze Try this logo to see how it looks

![logo-34](https://cloud.githubusercontent.com/assets/52113/7758422/7dda7590-0001-11e5-88b4-8518aac7c3ab.png)

**Comment by baimingze** [comment]
Beautiful, I have added this.

**Comment by ypriverol** [comment]
@Mingze we should add To the Header the Name of the Project Like: Datasets Discovery Index like cluster has 
![screen shot 2015-05-22 at 14 14 49](https://cloud.githubusercontent.com/assets/52113/7771125/07c13934-008d-11e5-9939-013509f643ff.png)
