### ISSUE TITLE
The Breadcrumbs needs to be the label and not the id

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#18]
![screen shot 2015-05-22 at 14 39 15](https://cloud.githubusercontent.com/assets/52113/7771625/8ab02f82-0090-11e5-90aa-4005d0df8a06.png)

**Comment by ypriverol** [comment]
@baimingze when a user search by some of the facet the Breadcrumbs use the id (2519 or the one from the facet) .It should be replace in the interface by the label. For example if you filter by Human you should use the human label and not the 9016 id.

**Comment by baimingze** [comment]
done
