### ISSUE TITLE
The code stype shpuld be close to this in the API help 

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#21]
![screen shot 2015-05-22 at 15 25 20](https://cloud.githubusercontent.com/assets/52113/7772568/f07dc22e-0096-11e5-8fb2-555de349fdbd.png)

**Comment by baimingze** [comment]
![snapshot2](https://cloud.githubusercontent.com/assets/3970400/7810605/515d380c-039b-11e5-9aa1-add66a986c9a.png)


Is this ok?

**Comment by ypriverol** [comment]
@baimingze OK!! really nice, please check also the links in the menu because they are not working properly.

**Comment by baimingze** [comment]
all doen
