### ISSUE TITLE
The ison for a peptideAtlas dataset do not work

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#26]
The proteomics icon do not works for:

http://localhost:8000/app/dataset.html#/PXD000085*PeptideAtlas

![screen shot 2015-06-02 at 14 15 56](https://cloud.githubusercontent.com/assets/52113/7936569/fa0da504-0931-11e5-895b-268cb0a6921c.png)

**Comment by baimingze** [comment]
finishied
