### ISSUE TITLE
We should add to the wordcloud the other resources

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#28]
All databases should be added to the wordcloud:
- [x] PeptideAtlas
- [x] MassIVE

**Comment by baimingze** [comment]
now I have just set the Data_Protocol and Sample_Protocol to ```<null>```

to hide the choice in fields will need some efforts, we can put it in a lower priority if you like.

**Comment by ypriverol** [comment]
@baimingze  if the data is only provided for description we should try to make it available only for description. The null solution is not nice, then I prefer to remove the databases that do not contain the information, if is to complex.

**Comment by baimingze** [comment]
@ypriverol now please checkout and try the limitation strategy is ok or not.

**Comment by baimingze** [comment]
done and close
