### ISSUE TITLE
Update the Help docuemntation

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#33]
@baimingze I just created the help documentation for the project. IT would be nice to update the HTML page with the information of this documentation, including the menu, etc. Here the link to the documentation https://github.com/BD2K-DDI/datadiscoveryindex/blob/master/docs/DDI-Help-Page.pdf

In my view this is high-priority.

**Comment by ypriverol** [comment]
@baimingze only the links are not working, all the information is correct know. Great job!!!

**Comment by baimingze** [comment]
Thank you, @ypriverol . I have found the reason of the bug. But it will take time to make the change, because of the Angular framework relevant codes need to be reset.

**Comment by ypriverol** [comment]
@baimingze is fine, we need to only address this ins the future.

**Comment by baimingze** [comment]
done
