### ISSUE TITLE
some refinements in the interface

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#34]
I was doing some testing with @ruiwanguk and here some of his feedback and I'm agree:
 - [x] We should remove from Latest Datasets and Most Accessed the bullet from every datasets because we already have the icon.
 - [x] For the dataset view we should merge in one box the description, the Data Protocol and finally the Sample protocol, like merge the first box with the second box (Protocol). 
 - [x] Change Related Datasets with Similar Datasets.

**Comment by baimingze** [comment]
done
