### ISSUE TITLE
Small refinements when information is not present in dataset View

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#36]
- [x] When the Sample, Data or Abstract is not provided (http://localhost:8000/app/dataset.html#/PXD000003*PeptideAtlas) The headline should be removed because do not contain that information. For example in pubmed when the abstract is not present them the system do not show the ABSTRACT word see example http://www.ncbi.nlm.nih.gov/pubmed/24304322

- [x] It would be good for the publication also show the information of the authors, and the citation like pubmed shows, because the users are use to that. For example http://www.ncbi.nlm.nih.gov/pubmed/24870542

**Comment by baimingze** [comment]
done
