### ISSUE TITLE
Refine in the worldCloud

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#37]
@baimingze Perhaps we should think about the css to have both in the same line, aligned, like the other charts. 

![screen shot 2015-06-05 at 12 01 36](https://cloud.githubusercontent.com/assets/52113/8004818/d48f7ed8-0b7a-11e5-858d-6600da155240.png)

**Comment by ypriverol** [comment]
@baimingze Some ideas about the wordcloud:
 - [ ] It would be nice to have a different type of letter, try with some of them including the size, etc. I will 
       allow us to have more words in the block. 
       You can read more about this topic her:
          - http://ceur-ws.org/Vol-782/ZhangAndHeflin_COLD2011.pdf
          - http://www.nngroup.com/articles/tag-cloud-examples/
          - http://www.jasondavies.com/wordcloud/#http%3A%2F%2Fcomputationalproteomic.blogspot.co.uk%2F2015%2F05%2Fa-trans-proteomic-pipeline-tpp-docker.html

I was playing with the letter to be able to put more words. I think about this visualisation. For example Arial works very nice.

**Comment by baimingze** [comment]
```https://github.com/timdream/wordfreq``` may help us to do the stem works
