### ISSUE TITLE
Some comments from the meeting

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#40]
- [x] We need to have a different in the Dataset View between the Dataset and the Publication information.
- [x] Perhaps it would be better to have the same icon in the dataset view for the publications that RNACentral is using. 
- [x] The alignment in the statistics. 
- [x] The header should look more like RNA Central 
- [x] Remove the footer information related with EBI. 

![screen shot 2015-06-05 at 16 08 08](https://cloud.githubusercontent.com/assets/52113/8008948/486893e0-0b9d-11e5-89bb-bd6bbf096279.png)

**Comment by baimingze** [comment]
done
