### ISSUE TITLE
Improve the message if the web-service is unavilable

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#41]
@mingze we should try to improve the message system if the web service is unavailable
![screen shot 2015-06-11 at 10 28 25](https://cloud.githubusercontent.com/assets/52113/8103964/d7569ee0-1024-11e5-934c-fb99f4e03c68.png)
. 

Instead of this message we can have a landing page that shows the service is not online, some examples: 

- http://www.piworld.com/post/outages-one-reason-multi-channel-marketing-is-important-printers-tom-marin/

- http://blogs.telegraph.co.uk/technology/files/2009/07/picture-43-460x279.png

**Comment by baimingze** [comment]
done
