### ISSUE TITLE
numbers of visits

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#43]
@baimingze Remember that we need to add the number to the most accessed datasets following the same pattern that twitter follow something like:
  - icon the views 1 then if is more than 1000 use 1k .. etc

**Comment by baimingze** [comment]
that's a great idea, should I create a issue in DDI-web-service?
@ypriverol

**Comment by ypriverol** [comment]
Yes please.. also for all the issues in the front end that needs refactoring in the web-services.

**Comment by ypriverol** [comment]
@baimingze the functionality is already implemented here:
 
    {
      "id": "PXD001418",
      "source": "pride",
      "title": "Comprehensive Assessment of Proteins Regulated by Dexamethasone Reveals Novel Effects in Primary Human Peripheral Blood Mononuclear Cells - nuclear proteins of inflammatory stimulated cells",
      "description": "Inflammation is a physiological process involved in many diseases. Monitoring proteins involved in regulatory effects may help to improve our understanding of inflammation. We have analyzed proteome alterations induced in peripheral blood mononuclear cells (PBMCs) upon inflammatory activation in great detail using high resolution mass spectrometry. Moreover, the activated cells were treated with dexamethasone to investigate their response to this antiphlogistic drug. From a total of 6886 identified proteins, 469 proteins were significantly regulated upon inflammatory activation. Most of these proteins were counter-regulated by dexamethasone, with some exceptions concerning members of the interferon-induced protein family. To confirm some of these results, we performed targeted MRM analyses of selected peptides. The inflammation-induced up-regulation of proteins such as IL-1beta, IL-6, CXCL2 and GROα was confirmed, however with strong quantitative inter-individual differences. Furthermore, the inability of dexamethasone to down-regulate inflammation-induced proteins such as PTX3 and TSG6 was clearly demonstrated. In conclusion, the relation of cell function as well as drug-induced modulation thereof was successfully mapped to proteomes, suggesting targeted analysis as a novel and powerful drug evaluation method. While most consequences of dexamethasone were found compatible with the expected way of action, some unexpected but significant observations may relate with adverse effects.",
      "keywords": null,
      "organisms": null,
      "visitCount": 2,
      "publicationDate": "20141104"
    },

The property visitCount contains the value of the number of visits.

**Comment by baimingze** [comment]
done
