### ISSUE TITLE
not Datasets for MEtabolomeWorkbench or Metabolights in the database page

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#45]
@baimingze the database page do not sohws any dataset for the metabolome workbench or metaboligths. 

![screen shot 2015-06-18 at 11 05 25](https://cloud.githubusercontent.com/assets/52113/8228849/f6b4de7a-15a9-11e5-9e9b-8d4b674e87ca.png)

**Comment by baimingze** [comment]
done
