### ISSUE TITLE
Metabolomics Workbench datasets

### ISSUE THREAD

**Issue by noedelta** [BD2K-DDI/ddi-web-app#46]
![image](https://cloud.githubusercontent.com/assets/7516607/8233687/8f1b6f38-15cf-11e5-850f-411e7704e7d9.png)

After selecting Metabolomics and clicking in the first dataset you have something like this:

![image](https://cloud.githubusercontent.com/assets/7516607/8233631/3f276270-15cf-11e5-8fae-203993e2916c.png)

Maybe can the link be disable?

**Comment by baimingze** [comment]
done
