### ISSUE TITLE
Clicking twice in the same omic group

### ISSUE THREAD

**Issue by noedelta** [BD2K-DDI/ddi-web-app#48]
When you click the second time for an omics group instead of search again for the same omic group the query is clean. I understand the behaviour, however if you see genomics after clicking proteomics a second time it is a bit confusing
Steps:
1-Click in a omic group (i.e. proteomics)
![image](https://cloud.githubusercontent.com/assets/7516607/8234060/a735f03c-15d1-11e5-96c9-99dcde67b01d.png)
2.Click again in the same group (proteomics) the results are reset and you see the default one (genomics)
![image](https://cloud.githubusercontent.com/assets/7516607/8234130/fda3fe96-15d1-11e5-868e-fe2d8e0735c8.png)

**Comment by baimingze** [comment]
done
