### ISSUE TITLE
Style guidelines

### ISSUE THREAD

**Issue by noedelta** [BD2K-DDI/ddi-web-app#49]
In case the project would be deploy under ebi.ac.uk I will recommend reviewing some of the guidelines.
http://www.ebi.ac.uk/web/style is specially useful the part related with patters http://www.ebi.ac.uk/web/style/patterns icons together with the resources http://www.ebi.ac.uk/web_guidelines/images/icons/

**Comment by baimingze** [comment]
perfect, thanks!
