### ISSUE TITLE
When I start to click the resource a wrong behaviour starts, see image below

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#5]
@baimingze after clicking some of the page and go back and foward, a wrong layout starts to appear, here the image. 

![screen shot 2015-05-20 at 15 31 40](https://cloud.githubusercontent.com/assets/52113/7728189/8d606ecc-ff05-11e4-86ad-ea1d419a296e.png)

**Comment by baimingze** [comment]
done
