### ISSUE TITLE
Some refinements that needs to be done

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#50]
- [x] Home page:
  - [x] Home Page - Statistics:
     - [x] Change all the words to lower cases. 
     - [x] Change ‘Repositories / Databases’ to ‘ repositories’
     - [x] Change ‘Species / Organisms’ to ‘species’
     - [x] Remove the word Different for each line 
  -  [x] Makes the Search Box little more bigger
  
  - [x] Home Page - Word cloud:
      - [x] Change ‘Repo’ to ‘Repository’
      - [x] Add some hints to each word with number of datasets datasets for each word.
      - [x] Remove the combo box and use tree tooltips [ ] description [ ] sample [ ] data all the data 
             should be retrieved from omics.  
  - [x] Home Page - Bubble plot:
      - [x] The bigger bubbles should be a more "interesting" color like orange or blue or read, not green. 
      - [x] For the tooltips, I would suggest to say ‘123 datasets’ instead of just ‘123'

  - [x] Home Page - Pie chart:
      - [x] When click on ‘Proteomics’, then in the search results page remove ‘Proteomics’ as a filter(just disable it). 

  - [x] Home Page - Latest Datasets & Most Accessed Datasets
      - [x] It would be nice to have a tooltip for the icons, the users won’t know the meaning of these 
            icons by default. 
      - [x] It would be nice to add the icon for the number of visits and the number itself.

Search
 - [x] (It 's a feature :smile: )After clicking on ‘Show results for Proteomics’, I cannot switch to ‘Metabolomics’ or ‘Genomics’. 
 - [x] It would be nice to have highlighting when you search or filtering
 - [ ] In the search box, when there is no query, just show all the results instead of warning the users 
            of query is too short
 - [x] Pagination seems to be a bit strange, it would be nice to show the first and the last page 
            number all the time, so users can to the beginning or the end. 
 - [ ] Sorting, a icon or a text is needed to show whether it is descending or ascending. 
 - [x] Sorting, I am not sure sorting by title makes much sense. 
 - [x] Metabolomics dataset doesn’t show any icon
 - [x] In addition to organisms, it would nice to see tissues, diseases in the search results as well. 
 - [x] It would be nice to highlight the source database in the search results. 
 - [x] In search results, change ‘Made public’ to ‘Publication date’
 - [ ] I would suggest change the filters according to the omics dataset type, for example, it doesn’t 
 make much sense to show proteomics instrument filters for genomics. (Nice recomendation but  for future) 
 - [x] The header that states ‘???? results for search term’ seems redundant as you have this 
              number on the search result table. 
 - [ ] Some datasets don’t have publication date, but still shown as the highest when sort by 
              publication date
 - [ ] In the filters, ‘Not available’ is not a good candidate for filtering.

**Comment by ypriverol** [comment]
@baimingze Can we close this issue?

**Comment by baimingze** [comment]
yes，sure
