### ISSUE TITLE
bugs from 23/10/2015

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#59]
Some bugs that needs to be fixed:
- [x] In the main page in the most accessed datasets the text sometime is overlap. (https://raw.githubusercontent.com/BD2K-DDI/specifications/master/docs/debug/23-10-2015/mostaccesed.png)
- [ ] Some of the databases do not provide the number of datasets (https://raw.githubusercontent.com/BD2K-DDI/specifications/master/docs/debug/23-10-2015/databases.png)
- [x] The social media buttons sometimes are overlapped with the text (https://raw.githubusercontent.com/BD2K-DDI/specifications/master/docs/debug/23-10-2015/media.png)
- [x] I filter the global search for Massive (https://raw.githubusercontent.com/BD2K-DDI/specifications/master/docs/debug/23-10-2015/massive1.png) and the results shows for 2014 (17) experiments, then i chose this 17 experiments and the results are empty (https://raw.githubusercontent.com/BD2K-DDI/specifications/master/docs/debug/23-10-2015/massive2.png)
- [x] Some of the description are to long for the search page and needs to be short example (https://raw.githubusercontent.com/BD2K-DDI/specifications/master/docs/debug/23-10-2015/tolongdescription.png)
- [x] Responsive template (https://raw.githubusercontent.com/BD2K-DDI/specifications/master/docs/debug/23-10-2015/responsive-template.png). @baimingze here we need to text carefully all the features in desktop, mobile, etc. Remember that most of the people will access to this resource from their mobiles.

**Comment by baimingze** [comment]
the last one: Responsive template, we need to retest after redeploy, may be I get it done before.
