### ISSUE TITLE
A new repository was added

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#6]
The new dataset domain was added (metabolome_workbench) has been successfully indexed in the test environment. Please when you have some time added to the interface.

**Comment by baimingze** [comment]
In the facet view, the name of this repo is " MetabolomicsWorkbench". Should I choose this one?

**Comment by ypriverol** [comment]
@baimingze  Is the code updated.

**Comment by ypriverol** [comment]
@baimingze some testing around Metabolome Workbench:
  1- When I search for metabolome workbech using the piechart, nothing happened, we need to check 
      the search.
  2- The Freq terms option needs to include the Metabolome Workbench.

**Comment by baimingze** [comment]
done.
