### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#63]
@mingze We have an strange behavior in the page, see here the example: https://raw.githubusercontent.com/BD2K-DDI/specifications/master/docs/debug/07-12-2015/Screen%20Shot%202015-12-07%20at%2011.40.15.png

**Comment by ypriverol** [comment]
@migze When I try to see the metadata associated with the dataset, html source:

<meta content={{meta_dataset_title}} name="dataset_title">
    <meta content={{meta_dataset_abstract}} name="dataset_abstract">
    <meta content={{meta_dataset_identifier}} name="dataset_identifier">

We need to fix this in order to be index by the community.

**Comment by baimingze** [comment]
I am not sure under this situation, if metadata has been indexed by search engines or not.

If you use "wget http://wwwdev.ebi.ac.uk/Tools/ddi/#/dataset/pride/PXD001020"  or "curl http://wwwdev.ebi.ac.uk/Tools/ddi/#/dataset/pride/PXD001020", you can get nothing about PXD001020 at all.

**Comment by ypriverol** [comment]
@baimingze we need to fix this as soon as possible. Here what I would like to have:

> here we will add the original dataset URL in the database. 

\<link rel="canonical" href="http://www.ebi.ac.uk/pride/archive/projects/PXD001677"/\> 

> Also we will add our URL 

\<link rel="canonical" href="http://www.ebi.ac.uk/Tools/omicsdi/#/dataset/pride/PXD001677"/\>  

> Then this information

\<meta name="citation_title" content="SIM-XL: a powerful and user-friendly "/\>
\<meta name="citation_author" content="Diogo Borges Lima"/\>
\<meta name="citation_author" content="Paulo Costa Carvalho"/\>
\<meta name="citation_pubdate" content="02/02/2015"/\>

**Comment by baimingze** [comment]
@ypriverol done, please have a check
