### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#72]
@baimingze 
  We will need an icon for: 
    - Transcriptomics
    - Multiomics (Probably here instead of using only one color, you can use multicolor someting like the 
      almetric byu with our colors. 
    - I will explore the idea of adding meta-genomics then have an icon ready.

**Comment by ypriverol** [comment]
@baimingze are these icos already created.

**Comment by ChrisShen93** [comment]
Transcriptomics and Multiomics have been done, except the meta-genomics

**Comment by baimingze** [comment]
Transcriptomics and Multiomics have been done, except the meta-genomics

**Comment by ypriverol** [comment]
+1
