### ISSUE TITLE
issues in the new chart 

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#73]
@baimingze the new chart produce an error in the button. 
check image: 

<img width="397" alt="screen shot 2016-05-17 at 16 13 22" src="https://cloud.githubusercontent.com/assets/52113/15325522/f60db34a-1c4a-11e6-99f0-66dd1364e99d.png">

Also I'm unable to see the chart if i click the omics button.

**Comment by ypriverol** [comment]
@baimingze I guess the omics piechart can be the same. we can use the new Amaizing barchat for the repositories and the piechart for the omics type.

What do you think?

**Comment by baimingze** [comment]
Yes, sure. That is what we thought and what we did. But don't know why this happen on your computer. It works fine on mine. 

i.e. 
![qq20160517230949](https://cloud.githubusercontent.com/assets/3970400/15327615/aa31da52-1c84-11e6-8f5b-8f9988a598cc.png)
