### ISSUE TITLE
Dataset Page completely broken (Urgent)

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#76]
@baimingze the dataset view is completely broken (see the example). Please update this and commit the code as soon as possible.  

<img width="1225" alt="screen shot 2016-06-15 at 17 56 17" src="https://cloud.githubusercontent.com/assets/52113/16089445/08fe554c-3323-11e6-8df0-525911fe95c1.png">

**Comment by baimingze** [comment]
Could you see the console's output by pressing the F12 button?  
It's working fine on my computer. 
![qq20160616092132](https://cloud.githubusercontent.com/assets/3970400/16102640/0a60252e-33a4-11e6-962f-42f9bf5f4f60.png)

**Comment by ypriverol** [comment]
close
