### ISSUE TITLE
discuss integration

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#78]
@baimingze about the integration with discuss:
 
- [x] The discuss panel should be located for every dataset below the publication/similar panel and before the footer where we put the institutions, etc. and not below the footer as is in the example image. 

- [x] The discuss component should contains only the comments relative to the dataset under review.  

<img width="1230" alt="screen shot 2016-06-15 at 18 07 46" src="https://cloud.githubusercontent.com/assets/52113/16089886/0c675efc-3325-11e6-8464-41ccafdd70bc.png">

**Comment by ypriverol** [comment]
@baimingze great work guys. Can you make closer the disquss 

<img width="1225" alt="screen shot 2016-06-17 at 10 05 53" src="https://cloud.githubusercontent.com/assets/52113/16145954/7a5f8278-3473-11e6-8e88-69593c114534.png">

**Comment by baimingze** [comment]
done
