### ISSUE TITLE
Sysnonyms are not working in the web

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#80]
@baimingze for some reason the text in the web is split and the synonyms are not shown. See the example:

<img width="805" alt="screen shot 2016-07-01 at 17 08 15" src="https://cloud.githubusercontent.com/assets/52113/16527420/b4dc2a5a-3fae-11e6-9c02-32a12aa684bd.png">

**Comment by baimingze** [comment]
Hi Yasset, could you send me the enrichmentinfo for me like this url "http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/enrichment/getEnrichmentInfo?accession=GPM32320004830&database=gpmdb"?   

I don't have an enrichment DB in my local computer, and can't get the info from the url above.

**Comment by ypriverol** [comment]
[gpmdb.zip](https://github.com/BD2K-DDI/ddi-web-app/files/344457/gpmdb.zip)

**Comment by baimingze** [comment]
done
