### ISSUE TITLE
Not information display when enrichment is empty 

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#83]
@baimingze when the enrichment is null. The page do not shown the information of abstract, ..
Can you check that. 

<img width="808" alt="screen shot 2016-07-08 at 16 41 43" src="https://cloud.githubusercontent.com/assets/52113/16692935/e5af2048-452a-11e6-919c-0493fcbc3f9e.png">

**Comment by baimingze** [comment]
done!
