### ISSUE TITLE
move to local path the ebi js css

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#84]
@baimingze when the ebi is dwon the web fails completely because all the css and js dependencies. See today error. 

<img width="785" alt="screen shot 2016-07-10 at 10 29 39" src="https://cloud.githubusercontent.com/assets/52113/16712785/86f142ce-4689-11e6-96a9-6685b91a1a64.png">

<img width="1279" alt="screen shot 2016-07-10 at 10 29 57" src="https://cloud.githubusercontent.com/assets/52113/16712787/8d73d86e-4689-11e6-8dda-611e05ac4ed2.png">

**Comment by baimingze** [comment]
done
