### ISSUE TITLE
The barchar in the the statistics in the home page don't work for Expression Atlas

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#86]
Expression Atlas is not working in the barchar. When you click it try to look for a different domain "Expression Atlas Experiments".

<img width="383" alt="screen shot 2016-07-18 at 10 25 05" src="https://cloud.githubusercontent.com/assets/52113/16910728/2ca7a034-4cd2-11e6-9e5d-7b64e7d77aa9.png">

**Comment by baimingze** [comment]
done
