### ISSUE TITLE
Remove the name of repositories and omicstype from axis

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#87]
@baimingze the current axis for repositories and omicstype is almost pointless because you can't ready the text. 

<img width="377" alt="screen shot 2016-07-18 at 13 47 07" src="https://cloud.githubusercontent.com/assets/52113/16915191/491b2be8-4cee-11e6-90fd-fb640feb702f.png">

**Comment by baimingze** [comment]
done. 
In my first idea, it's a "hint" for user to find out the full name of the repositories/omics type.
