### ISSUE TITLE
letter in the similarity chord diagram truncated

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#90]
@baimingze for most of the datasets the ID of the dataset is truncated. We need to find a way to avoid this truncation by decrease the size of the letter or look for other position. 

<img width="461" alt="screen shot 2016-07-18 at 15 15 00" src="https://cloud.githubusercontent.com/assets/52113/16917725/b5b77a66-4cfa-11e6-9ef9-a33b0df32fa4.png">

**Comment by baimingze** [comment]
how about use a tooltip to show the full name when the truncated name is hovered on?

**Comment by baimingze** [comment]
Have you adjusted some settings of the omicsdi system or browser? Please refer to another example: http://wwwdev.ebi.ac.uk/Tools/omicsdi/#/dataset/pride/PRD000192

**Comment by ypriverol** [comment]
No actually the error was reported from somebody else. Have you try to give other orientation. Probably more vertical in the line with the chord diagram. Please also add the hovered in hte meantime.

**Comment by baimingze** [comment]
tooltip added
