### ISSUE TITLE
Disqus enhancement

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#92]
@baimingze the discus for each dataset comment has always the title "OmicsDI Dataset" this is really to generic. Probably would be good to have more customization like the title of the dataset or the combination of Repository - RepositoryID. See the image: 

<img width="620" alt="screen shot 2016-07-19 at 10 02 11" src="https://cloud.githubusercontent.com/assets/52113/16944404/4bcf44be-4d98-11e6-928b-e5bdbd0ad48c.png">

**Comment by baimingze** [comment]
done

**Comment by baimingze** [comment]
The code is ready, bu I guess we need to delete the whole site to change the titles. https://omicsdi.disqus.com/admin/settings/advanced/

**Comment by ypriverol** [comment]
what means the whole site ?

**Comment by ypriverol** [comment]
Done
