### ISSUE TITLE
Data set misclassification

### ISSUE THREAD

**Issue by prvst** [BD2K-DDI/ddi-web-app#94]
[This](http://www.omicsdi.org/#/dataset/pride/PXD002880) entry shows under the multiomics filter, but it seems to be present only in PRIDE. Is this an error?

**Comment by baimingze** [comment]
http://www.omicsdi.org/ws/dataset/get?acc=PXD002880&database=pride

The web service returned: 
```
"omics_type":["Proteomics","Multi-Omics"]
```

**Comment by baimingze** [comment]
I will add an issue in web service.
