### ISSUE TITLE
problem with the dataset similarity chord

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#96]
@baimingze in the similarity chord in this example http://www.omicsdi.org/#/dataset/metabolomics_workbench/ST000054

We have two datasets with the same id.

**Comment by baimingze** [comment]
please check this url, may be some of the code in web service has changed some thing:
http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/enrichment/getSimilarityInfo?accession=ST000054&database=MetabolomicsWorkbench  returns a lot of datasets, and the front end system can draw the right chord.

http://www.omicsdi.org/ws/enrichment/getSimilarityInfo?accession=ST000054&database=MetabolomicsWorkbench returns only two datasets, but it looks not right.
