### ISSUE TITLE
Some refinements and bugs in the Web

### ISSUE THREAD

**Issue by ypriverol** [BD2K-DDI/ddi-web-app#97]
http://www.omicsdi.org/#/

- [x] top left panel: description, sample, data should all be first letter uppercase.

- [x] Right panel: Repos **->** Resources

- [x] Any dataset page, for example http://www.omicsdi.org/#/dataset/pride/PXD002039 :
After clicking on "...more" for ABSTRACT, SAMPLE PROTOCOL, etc: Just before the "less", the last dot '.' of the text is missing. I also suggest to add some kind of special character before/around the "less", for example " [less]".

- [x] http://www.omicsdi.org/#/about : In particular, OmicsDI identifiers groups of **->** In particular, OmicsDI identifies groups of

- [x] http://www.omicsdi.org/#/help
"If you are interested in the architecture and the metadata that the resource should provide see section ?."
Here @baimingze we should forward the user to the github page.

- [x] "The OmicsDI web application has two main different way of navigate the data: (i) using the home page navigation blocks or (ii) the search box." **->** "The OmicsDI web application offers two main access modes: (i) using the home page navigation panels or (ii) the search box."

- [x] http://www.omicsdi.org/#/dataset/pride/PXD003436
Sorry, this publication's infomation has not been loaded in the Indexer, please go directly to the PUBMED or the Altmetric. **->** Sorry, this publication's information has not been loaded in the indexer, please go directly to PUBMED or Altmetric.

- [x] Can we remove the but little lines around the plot (similarity chord). See image. 

![pastedgraphic-1](https://cloud.githubusercontent.com/assets/52113/17051267/b1d26b02-4fef-11e6-834f-c8ddd3824b6d.png)

- [x] The letter here overlap completly the page, Can we solve this issue. 

![pastedgraphic-4](https://cloud.githubusercontent.com/assets/52113/17051363/38d5d9d6-4ff0-11e6-8a49-6ec0b11fe429.png)

- [x] Problem with undefined. 

![pastedgraphic-5](https://cloud.githubusercontent.com/assets/52113/17051394/6e54fe02-4ff0-11e6-86b3-8a3d710d05c0.png)

- [x] On http://www.omicsdi.org/#/search?q=repository:%22ArrayExpress%22%20AND%20omics_type:%22Transcriptomics%22%20AND%20omics_type:%22Genomics%22, clicking on sorting up/down arrows doesn’t seem to change the order of experiments shown (for any of the ‘accession’, ‘Relevance’ or ‘Publication date’ categories)

- [x] The left-hand side search boxes for say Repository or tissue don’t seem to be functional yet? If I type say heart in Tissue text box and press enter, nothing happens. Here @baimingze when not value is provided we should disable the panel. 

<img width="291" alt="screen shot 2016-07-22 at 09 44 31" src="https://cloud.githubusercontent.com/assets/52113/17051490/f1e97b44-4ff0-11e6-969f-31a4d4f6c828.png">

**Comment by baimingze** [comment]
----
On http://www.omicsdi.org/#/search?q=repository:%22ArrayExpress%22%20AND%20omics_type:%22Transcriptomics%22%20AND%20omics_type:%22Genomics%22, clicking on sorting up/down arrows doesn’t seem to change the order of experiments shown (for any of the ‘accession’, ‘Relevance’ or ‘Publication date’ categories)


the sorting is not working any more in webservice
you got same result with different parameters, something may be changed in Ebeye.

http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/dataset/search?query=cancer*&facetcount=100&size=15&sortfield=id&order=ascending&start=0

http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/dataset/search?query=cancer*&facetcount=100&size=15&sortfield=id&order=descending&start=0

http://wwwdev.ebi.ac.uk/Tools/omicsdi/ws/dataset/search?query=cancer*&facetcount=100&size=15&sortfield=publication_date&order=descending&start=0

**Comment by baimingze** [comment]
About the "undefined issue", I can't reproduce the issue, could you please send me the url of this issue?
